[Config]
prefix        = "!"
owner_id      = "704106773660827690"
guild_id      = "901692268082249748"
app_id        = "1003151360012853288"
server_invite = "https://discord.gg/5T7nDZFGft"
permissions   = "414467812551"
status        = "with colors"

[Switches]
local_slash = false
